<?php

namespace App\Tests\Unit\Infrastructure\Youtube;

use App\Infrastructure\Filesystem\SubtitleWorkspaceManager;
use App\Infrastructure\Youtube\SubtitleDownloadException;
use App\Infrastructure\Youtube\SubtitlesUnavailableException;
use App\Infrastructure\Youtube\YtDlpSubtitleDownloader;
use PHPUnit\Framework\TestCase;

final class YtDlpSubtitleDownloaderTest extends TestCase
{
    public function testDownloadsRegularSubtitles(): void
    {
        $tempDir = $this->createTempDirectory();
        $argsLog = $tempDir.'/args.log';
        $binary = $this->createFakeYtDlpBinary($tempDir.'/fake-yt-dlp.php', 'regular', $argsLog);

        $downloader = $this->createDownloader($tempDir, $binary);
        $artifact = $downloader->download('https://www.youtube.com/watch?v=dQw4w9WgXcQ');

        self::assertFileExists($artifact->subtitleFilePath);
        self::assertStringEndsWith('.srt', $artifact->subtitleFilePath);
        self::assertFileExists($artifact->workspacePath);
        self::assertStringContainsString('--write-subs', file_get_contents($argsLog));
        self::assertStringContainsString('--no-write-auto-subs', file_get_contents($argsLog));

        $this->removePath($artifact->workspacePath);
        $this->removePath($tempDir);
    }

    public function testFallsBackToAutoGeneratedSubtitles(): void
    {
        $tempDir = $this->createTempDirectory();
        $argsLog = $tempDir.'/args.log';
        $binary = $this->createFakeYtDlpBinary($tempDir.'/fake-yt-dlp.php', 'auto', $argsLog);

        $downloader = $this->createDownloader($tempDir, $binary);
        $artifact = $downloader->download('https://youtu.be/dQw4w9WgXcQ');

        self::assertFileExists($artifact->subtitleFilePath);
        self::assertStringEndsWith('.srt', $artifact->subtitleFilePath);

        $log = file($argsLog, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        self::assertCount(2, $log);
        self::assertStringContainsString('--write-subs', $log[0]);
        self::assertStringContainsString('--write-auto-subs', $log[1]);

        $this->removePath($artifact->workspacePath);
        $this->removePath($tempDir);
    }

    public function testThrowsWhenSubtitlesAreUnavailable(): void
    {
        $tempDir = $this->createTempDirectory();
        $argsLog = $tempDir.'/args.log';
        $binary = $this->createFakeYtDlpBinary($tempDir.'/fake-yt-dlp.php', 'none', $argsLog);

        $downloader = $this->createDownloader($tempDir, $binary);

        $this->expectException(SubtitlesUnavailableException::class);
        try {
            $downloader->download('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
        } finally {
            $this->removePath($tempDir);
        }
    }

    public function testThrowsOnUnexpectedFailure(): void
    {
        $tempDir = $this->createTempDirectory();
        $argsLog = $tempDir.'/args.log';
        $binary = $this->createFakeYtDlpBinary($tempDir.'/fake-yt-dlp.php', 'fail', $argsLog);

        $downloader = $this->createDownloader($tempDir, $binary);

        $this->expectException(SubtitleDownloadException::class);
        try {
            $downloader->download('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
        } finally {
            self::assertSame(['.', '..'], scandir($tempDir.'/workspaces') ?: []);
            $this->removePath($tempDir);
        }
    }

    private function createDownloader(string $tempDir, string $binaryPath): YtDlpSubtitleDownloader
    {
        return new YtDlpSubtitleDownloader(
            new SubtitleWorkspaceManager($tempDir.'/workspaces'),
            $binaryPath,
            10,
        );
    }

    private function createTempDirectory(): string
    {
        $dir = sys_get_temp_dir().'/telegram-bot-'.bin2hex(random_bytes(4));
        if (!mkdir($dir, 0775, true) && !is_dir($dir)) {
            self::fail(sprintf('Unable to create temp directory: %s', $dir));
        }

        return $dir;
    }

    private function createFakeYtDlpBinary(string $path, string $mode, string $argsLog): string
    {
        $script = sprintf(<<<'PHP'
#!/usr/bin/env php
<?php
$args = $argv;
array_shift($args);
file_put_contents(%s, implode(' ', $args).PHP_EOL, FILE_APPEND);

$workspace = null;
for ($i = 0, $count = count($args); $i < $count; $i++) {
    if ($args[$i] === '--paths') {
        $workspace = $args[$i + 1] ?? null;
    }
}

$mode = %s;
$hasWriteSubs = in_array('--write-subs', $args, true);
$hasWriteAutoSubs = in_array('--write-auto-subs', $args, true);

if ($mode === 'fail') {
    fwrite(STDERR, 'simulated yt-dlp failure');
    exit(2);
}

if ($workspace !== null && !is_dir($workspace)) {
    mkdir($workspace, 0775, true);
}

if ($mode === 'regular' && $hasWriteSubs && !$hasWriteAutoSubs) {
    file_put_contents($workspace.'/regular.srt', "1\n00:00:00,000 --> 00:00:01,000\nregular\n");
}

if ($mode === 'auto' && $hasWriteAutoSubs) {
    file_put_contents($workspace.'/auto.srt', "1\n00:00:00,000 --> 00:00:01,000\nauto\n");
}

exit(0);
PHP,
            var_export($argsLog, true),
            var_export($mode, true),
        );
        file_put_contents($path, $script);
        chmod($path, 0755);

        return $path;
    }

    private function removePath(string $path): void
    {
        if (is_file($path) || is_link($path)) {
            @unlink($path);
            return;
        }

        if (!is_dir($path)) {
            return;
        }

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($path, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST,
        );

        foreach ($iterator as $item) {
            if ($item->isDir()) {
                @rmdir($item->getPathname());
                continue;
            }

            @unlink($item->getPathname());
        }

        @rmdir($path);
    }
}
