<?php

namespace App\Infrastructure\Youtube;

use App\Infrastructure\Filesystem\SubtitleWorkspaceManager;
use Symfony\Component\Process\Process;

class YtDlpSubtitleDownloader
{
    public function __construct(
        private SubtitleWorkspaceManager $workspaceManager,
        private string $ytdlpBin,
        private int $processTimeoutSeconds,
        private int $sleepMinSeconds,
        private int $sleepMaxSeconds,
        private int $http429Retries,
        private int $http429InitialDelaySeconds,
        private int $http429MaxDelaySeconds,
    ) {
    }

    public function download(string $youtubeUrl): SubtitleDownloadArtifact
    {
        if (!is_file($this->ytdlpBin) || !is_executable($this->ytdlpBin)) {
            throw new SubtitleDownloadException(sprintf('yt-dlp binary is not executable: %s', $this->ytdlpBin));
        }

        $workspace = $this->workspaceManager->createWorkspace();

        try {
            $subtitleFilePath = $this->attemptDownload($youtubeUrl, $workspace, false)
                ?? $this->attemptDownload($youtubeUrl, $workspace, true);

            if ($subtitleFilePath === null) {
                throw new SubtitlesUnavailableException('No subtitles were found for this video.');
            }

            return new SubtitleDownloadArtifact($subtitleFilePath, $workspace);
        } catch (SubtitleDownloadException $exception) {
            $this->workspaceManager->removePath($workspace);

            throw $exception;
        } catch (\Throwable $exception) {
            $this->workspaceManager->removePath($workspace);

            throw new SubtitleDownloadException(sprintf('Subtitle download failed: %s', $exception->getMessage()), 0, $exception);
        }
    }

    private function attemptDownload(string $youtubeUrl, string $workspace, bool $autoGenerated): ?string
    {
        $attempts = max(1, $this->http429Retries + 1);
        $delaySeconds = max(0, $this->http429InitialDelaySeconds);

        for ($attempt = 1; $attempt <= $attempts; $attempt++) {
            $this->politeSleep();

            $process = new Process($this->buildCommand($youtubeUrl, $workspace, $autoGenerated));
            $process->setTimeout($this->processTimeoutSeconds > 0 ? $this->processTimeoutSeconds : null);
            $process->run();

            if (!$process->isSuccessful()) {
                $output = $process->getErrorOutput()."\n".$process->getOutput();

                if ($this->looksLikeMissingSubtitles($output)) {
                    return null;
                }

                if ($this->looksLikeHttp429($output) && $attempt < $attempts) {
                    sleep($delaySeconds);
                    $delaySeconds = $this->nextBackoffDelay($delaySeconds);
                    continue;
                }

                throw new SubtitleDownloadException(sprintf(
                    'yt-dlp failed (%s subtitles): %s',
                    $autoGenerated ? 'auto-generated' : 'regular',
                    trim($process->getErrorOutput()) !== '' ? trim($process->getErrorOutput()) : trim($process->getOutput()),
                ), $process->getExitCode() ?? 1);
            }

            $subtitleFilePath = $this->findSubtitleFile($workspace);

            if ($subtitleFilePath === null) {
                return null;
            }

            return $subtitleFilePath;
        }

        return null;
    }

    /**
     * @return list<string>
     */
    private function buildCommand(string $youtubeUrl, string $workspace, bool $autoGenerated): array
    {
        return [
            $this->ytdlpBin,
            '--js-runtimes', 'deno',
            '--skip-download',
            '--paths', $workspace,
            '-o', '%(id)s.%(ext)s',
            ...($autoGenerated ? ['--write-auto-subs', '--no-write-subs'] : ['--write-subs', '--no-write-auto-subs']),
            '--convert-subs', 'srt',
            '--sub-langs', 'all',
            $youtubeUrl,
        ];
    }

    private function looksLikeHttp429(string $output): bool
    {
        $normalized = strtolower($output);

        return str_contains($normalized, 'http error 429') || str_contains($normalized, 'too many requests');
    }

    private function politeSleep(): void
    {
        $min = max(0, $this->sleepMinSeconds);
        $max = max($min, $this->sleepMaxSeconds);

        if ($max === 0) {
            return;
        }

        sleep(random_int($min, $max));
    }

    private function nextBackoffDelay(int $currentDelaySeconds): int
    {
        $max = max(0, $this->http429MaxDelaySeconds);

        if ($currentDelaySeconds <= 0) {
            return min(1, $max);
        }

        $next = $currentDelaySeconds * 2;

        return $max > 0 ? min($next, $max) : $next;
    }

    private function findSubtitleFile(string $workspace): ?string
    {
        $files = glob(rtrim($workspace, '/').'/*.srt') ?: [];

        return $files[0] ?? null;
    }

    private function looksLikeMissingSubtitles(string $output): bool
    {
        $normalized = strtolower($output);

        foreach ([
            'no subtitles',
            'requested subtitle',
            'requested subtitles',
            'subtitles not available',
            'no subtitle',
        ] as $needle) {
            if (str_contains($normalized, $needle)) {
                return true;
            }
        }

        return false;
    }
}
