<?php

namespace App\Infrastructure\Youtube;

use App\Infrastructure\Filesystem\SubtitleWorkspaceManager;
use Symfony\Component\Process\Process;

class YtDlpSubtitleDownloader
{
    public function __construct(
        private SubtitleWorkspaceManager $workspaceManager,
        private string $ytdlpBin,
        private int $processTimeoutSeconds,
    ) {
    }

    public function download(string $youtubeUrl): SubtitleDownloadArtifact
    {
        if (!is_file($this->ytdlpBin) || !is_executable($this->ytdlpBin)) {
            throw new SubtitleDownloadException(sprintf('yt-dlp binary is not executable: %s', $this->ytdlpBin));
        }

        $workspace = $this->workspaceManager->createWorkspace();

        try {
            $subtitleFilePath = $this->attemptDownload($youtubeUrl, $workspace, false)
                ?? $this->attemptDownload($youtubeUrl, $workspace, true);

            if ($subtitleFilePath === null) {
                throw new SubtitlesUnavailableException('No subtitles were found for this video.');
            }

            return new SubtitleDownloadArtifact($subtitleFilePath, $workspace);
        } catch (SubtitleDownloadException $exception) {
            $this->workspaceManager->removePath($workspace);

            throw $exception;
        } catch (\Throwable $exception) {
            $this->workspaceManager->removePath($workspace);

            throw new SubtitleDownloadException(sprintf('Subtitle download failed: %s', $exception->getMessage()), 0, $exception);
        }
    }

    private function attemptDownload(string $youtubeUrl, string $workspace, bool $autoGenerated): ?string
    {
        $process = new Process($this->buildCommand($youtubeUrl, $workspace, $autoGenerated));
        $process->setTimeout($this->processTimeoutSeconds > 0 ? $this->processTimeoutSeconds : null);
        $process->run();

        if (!$process->isSuccessful()) {
            if ($this->looksLikeMissingSubtitles($process->getErrorOutput()."\n".$process->getOutput())) {
                return null;
            }

            throw new SubtitleDownloadException(sprintf(
                'yt-dlp failed (%s subtitles): %s',
                $autoGenerated ? 'auto-generated' : 'regular',
                trim($process->getErrorOutput()) !== '' ? trim($process->getErrorOutput()) : trim($process->getOutput()),
            ), $process->getExitCode() ?? 1);
        }

        $subtitleFilePath = $this->findSubtitleFile($workspace);

        if ($subtitleFilePath === null) {
            return null;
        }

        return $subtitleFilePath;
    }

    /**
     * @return list<string>
     */
    private function buildCommand(string $youtubeUrl, string $workspace, bool $autoGenerated): array
    {
        return [
            $this->ytdlpBin,
            '--skip-download',
            '--paths', $workspace,
            '-o', '%(id)s.%(ext)s',
            ...($autoGenerated ? ['--write-auto-subs', '--no-write-subs'] : ['--write-subs', '--no-write-auto-subs']),
            '--convert-subs', 'srt',
            '--sub-langs', 'all',
            $youtubeUrl,
        ];
    }

    private function findSubtitleFile(string $workspace): ?string
    {
        $files = glob(rtrim($workspace, '/').'/*.srt') ?: [];

        return $files[0] ?? null;
    }

    private function looksLikeMissingSubtitles(string $output): bool
    {
        $normalized = strtolower($output);

        foreach ([
            'no subtitles',
            'requested subtitle',
            'requested subtitles',
            'subtitles not available',
            'no subtitle',
        ] as $needle) {
            if (str_contains($normalized, $needle)) {
                return true;
            }
        }

        return false;
    }
}
